fullnameOverride: tryback

# crunchyImage: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres:ubi8-14.7-0

postgresVersion: 14

instances:
  name: employee # high availability
  replicas: 2
  dataVolumeClaimSpec:
    storage: 2Gi
    storageClassName: netapp-block-standard
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
  replicaCertCopy:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

pgBackRest:
  # image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest:ubi8-2.41-4
  retention: "2" # Ideally a larger number such as 30 backups/days
  # If retention-full-type set to 'count' then the oldest backups will expire when the number of backups reach the number defined in retention
  # If retention-full-type set to 'time' then the number defined in retention will take that many days worth of full backups before expiration
  retentionFullType: count
  repos:
    schedules:
      full: 0 8 * * *
      incremental: 0 0,4,12,16,20 * * *
    volume:
      accessModes: "ReadWriteOnce"
      storage: 1Gi
      storageClassName: netapp-file-backup
  repoHost:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  sidecars:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  s3:
    enabled: true
    createS3Secret: true
    # the s3 secret name 
    s3Secret: s3-pgbackrest
    s3Path: "/xxxx"
    # s3UriStyle is host or path
    s3UriStyle: path
    # bucket specifies the S3 bucket to use,
    bucket: "xxxx"
    # endpoint specifies the S3 endpoint to use.
    endpoint: "xxxx"
    # region specifies the S3 region to use. If your S3 storage system does not
    # use "region", fill this in with a random value.
    region: "ca-central-1"
    # key is the S3 key. This is stored in a Secret.
    key: "xxxx"
    # keySecret is the S3 key secret. This is stored in a Secret.
    keySecret: "xxxx"

patroni:
  postgresql:
    pg_hba: "host all all 0.0.0.0/0 md5"
    parameters:
      shared_buffers: 16MB # default is 128MB; a good tuned default for shared_buffers is 25% of the memory allocated to the pod
      wal_buffers: "64kB" # this can be set to -1 to automatically set as 1/32 of shared_buffers or 64kB, whichever is larger
      min_wal_size: 32MB
      max_wal_size: 64MB # default is 1GB
      max_slot_wal_keep_size: 128MB # default is -1, allowing unlimited wal growth when replicas fall behind

proxy:
  pgBouncer:
    # image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbouncer:ubi8-1.18-0
    replicas: 2
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

# Postgres Cluster resource values:
pgmonitor:
  enabled: false
  exporter:
    # image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres-exporter:ubi8-5.0.4-0
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
